version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: 'chat_application'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/docker-data/psql:/var/lib/postgresql/data
volumes:
  db:
    driver: local